// Copyright (c) Meta Platforms, Inc. and affiliates.

/**
 * @file Playground scope coverage test.
 *
 * Validates that the generated playground scope includes every public
 * component exported from @khameleon/core/package.json, plus the expected
 * non-component scope entries (themes, icons, stylex, react, next/image).
 *
 * This test reads the generated file as text (rather than importing it)
 * because the scope imports @khameleon/core/* which requires a prior build step.
 * Instead we verify the generator produced the correct import/scope lines.
 *
 * Run: pnpm -F @khameleon/docsite test
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import {describe, it, expect, beforeAll} from 'vitest';

const GENERATED_SCOPE_PATH = path.resolve(
  __dirname,
  '../generated/playground-scope.ts',
);

const CORE_PKG_PATH = path.resolve(
  __dirname,
  '../../../../packages/core/package.json',
);

/**
 * Same skip pattern as generate-scope.mjs — non-component exports like
 * CSS files, utils, hooks, theme, etc.
 */
const SKIP =
  /\.(css|stylex)$|\/utils$|^\.\/(theme|hooks|utils|syntax|docs|groups|reset)|\.$/;

function getExpectedComponents(): string[] {
  const pkg = JSON.parse(fs.readFileSync(CORE_PKG_PATH, 'utf-8'));
  return Object.keys(pkg.exports ?? {})
    .filter(k => {
      if (SKIP.test(k)) {
        return false;
      }
      const name = k.replace('./', '');
      return /^[A-Z]/.test(name);
    })
    .map(k => k.replace('./', ''));
}

describe('playground-scope', () => {
  let expectedComponents: string[];
  let scopeContent: string;

  beforeAll(() => {
    expectedComponents = getExpectedComponents();
    if (!fs.existsSync(GENERATED_SCOPE_PATH)) {
      throw new Error(
        `Generated scope file not found at ${GENERATED_SCOPE_PATH}. ` +
          'Run `pnpm generate` (or `node scripts/generate-scope.mjs`) first.',
      );
    }
    scopeContent = fs.readFileSync(GENERATED_SCOPE_PATH, 'utf-8');
  });

  it('generated file exists and has the codegen header', () => {
    expect(scopeContent).toContain('@generated by scripts/generate-scope.mjs');
  });

  // ── Component coverage ─────────────────────────────────────────────────

  it('imports every PascalCase component from @khameleon/core', () => {
    const missing = expectedComponents.filter(
      name =>
        !scopeContent.includes(
          `import * as ${name} from '@khameleon/core/${name}';`,
        ),
    );
    expect(missing).toEqual([]);
  });

  it('has a scope entry for every component', () => {
    const missing = expectedComponents.filter(
      name => !scopeContent.includes(`'@khameleon/core/${name}': ${name},`),
    );
    expect(missing).toEqual([]);
  });

  it('has a barrel @khameleon/core entry that spreads all components', () => {
    expect(scopeContent).toContain("'@khameleon/core': {");
    const missing = expectedComponents.filter(
      name => !scopeContent.includes(`...${name},`),
    );
    expect(missing).toEqual([]);
  });

  it('component count matches core exports', () => {
    const importLines = scopeContent
      .split('\n')
      .filter(l =>
        l.match(/^import \* as \w+ from '@khameleon\/core\/[A-Z]/),
      );
    expect(importLines.length).toBe(expectedComponents.length);
  });

  // ── Non-component scope entries ────────────────────────────────────────

  it('includes react scope with hooks', () => {
    expect(scopeContent).toContain('react: {');
    expect(scopeContent).toContain('useState');
    expect(scopeContent).toContain('useCallback');
    expect(scopeContent).toContain('useMemo');
    expect(scopeContent).toContain('useEffect');
    expect(scopeContent).toContain('useRef');
  });

  it('includes stylex mock under both specifiers', () => {
    expect(scopeContent).toContain("'@stylexjs/stylex':");
    expect(scopeContent).toContain('stylex:');
    expect(scopeContent).toContain('stylexMock');
  });

  it('includes all theme entries (bare and /built subpath)', () => {
    expect(scopeContent).toContain("'@khameleon/theme-neutral':");
    expect(scopeContent).toContain("'@khameleon/theme-neutral/built':");
    expect(scopeContent).toContain("'@khameleon/theme-matcha':");
    expect(scopeContent).toContain("'@khameleon/theme-matcha/built':");
  });

  it('includes Theme controlled wrapper and tokens', () => {
    expect(scopeContent).toContain("'@khameleon/core/theme': {Theme:");
    expect(scopeContent).toContain(
      "'@khameleon/core/theme/tokens.stylex': khameleonTokens,",
    );
    expect(scopeContent).toContain('ControlledTheme');
    expect(scopeContent).toContain('SCOPE_THEMES');
  });

  it('includes lucide-react icons', () => {
    expect(scopeContent).toContain("'lucide-react': LucideIcons,");
    expect(scopeContent).toContain(
      "import * as LucideIcons from 'lucide-react';",
    );
  });

  it('includes all heroicon variants', () => {
    expect(scopeContent).toContain(
      "'@heroicons/react/16/solid': Heroicons16Solid,",
    );
    expect(scopeContent).toContain(
      "'@heroicons/react/20/solid': Heroicons20Solid,",
    );
    expect(scopeContent).toContain(
      "'@heroicons/react/24/outline': Heroicons24Outline,",
    );
    expect(scopeContent).toContain(
      "'@heroicons/react/24/solid': Heroicons24Solid,",
    );
  });

  it('includes next/image stub', () => {
    expect(scopeContent).toContain("'next/image':");
    expect(scopeContent).toContain("React.createElement('img', props)");
  });
});
