#!/usr/bin/env node
// Copyright (c) Meta Platforms, Inc. and affiliates.

/**
 * Generates apps/docsite/src/generated/playground-scope.ts
 *
 * Maps every Khameleon module available in the playground preview iframe.
 * This runs as part of `pnpm generate` (before dev/build) so new components
 * are picked up automatically — no manual maintenance needed.
 *
 * Run: node scripts/generate-scope.mjs
 */

import {readFileSync, writeFileSync, mkdirSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');
const CORE_PKG = resolve(ROOT, '../../packages/core/package.json');
const OUT = resolve(ROOT, 'src/generated/playground-scope.ts');

const HEADER = `// Copyright (c) Meta Platforms, Inc. and affiliates.

// @generated by scripts/generate-scope.mjs — do not edit manually`;

// Read core package.json exports and extract PascalCase component subpaths
const corePkg = JSON.parse(readFileSync(CORE_PKG, 'utf-8'));
const exportKeys = Object.keys(corePkg.exports ?? {});

const SKIP = /\.(css|stylex)$|\/utils$|^\.\/theme|^\.\/hooks|^\.\/utils|^\.\/syntax|^\.\/docs|^\.\/groups|^\.$|^\.\/reset/;

const components = exportKeys
  .filter((k) => {
    if (SKIP.test(k)) return false;
    const name = k.replace('./', '');
    return /^[A-Z]/.test(name);
  })
  .map((k) => k.replace('./', ''));

// Themes — add new themes here as they become available
const SCOPE_THEMES = [
  {pkg: '@khameleon/theme-neutral', name: 'neutralTheme', subpath: '/built'},
  {pkg: '@khameleon/theme-matcha', name: 'matchaTheme', subpath: '/built'},
];

// Heroicons variants — exposed alongside Lucide so playground snippets
// and shared template code that still imports from '@heroicons/react/*'
// keeps rendering. New docsite code authors against Lucide; these entries
// are purely for playground runtime compatibility.
const HEROICON_VARIANTS = [
  {path: '16/solid', alias: 'Heroicons16Solid'},
  {path: '20/solid', alias: 'Heroicons20Solid'},
  {path: '24/outline', alias: 'Heroicons24Outline'},
  {path: '24/solid', alias: 'Heroicons24Solid'},
];


// Build output — matches the structure of the previously committed scope.ts
const lines = [HEADER, ''];

// ── React ──────────────────────────────────────────────────────────────
lines.push("import React, {useState, useCallback, useMemo, useEffect, useRef} from 'react';");
lines.push('');

// ── StyleX mock ────────────────────────────────────────────────────────
// The playground transpiles code in-browser without the StyleX compiler, so the
// mock reimplements stylex.create/props: each property becomes an atomic class
// injected into a shared <style> sheet, so @container/@media/pseudo conditions
// apply instead of collapsing to the `default` value an inline style would force.
//
// create() returns `$$css: true` objects of class names — the same shape the real
// compiled stylex.props() understands, so `xstyle` passed into @khameleon/core components
// merges correctly too.
lines.push(`type PGStyleValue =
  | string
  | number
  | {[condition: string]: string | number};
type PGRule = Record<string, PGStyleValue>;

const PG_UNITLESS = new Set([
  'opacity', 'zIndex', 'fontWeight', 'lineHeight', 'flex', 'flexGrow',
  'flexShrink', 'order', 'gridColumn', 'gridRow', 'gridColumnStart',
  'gridColumnEnd', 'gridRowStart', 'gridRowEnd', 'columnCount', 'aspectRatio',
  'scale', 'tabSize',
]);

const PG_CAMEL_RE = /[A-Z]/g;
const pgKebab = (prop: string): string =>
  prop.startsWith('--')
    ? prop
    : prop.replace(PG_CAMEL_RE, m => '-' + m.toLowerCase());

const pgCssValue = (prop: string, value: string | number): string =>
  typeof value === 'number' && !PG_UNITLESS.has(prop) ? value + 'px' : String(value);

const pgHash = (input: string): string => {
  let h = 5381;
  for (let i = 0; i < input.length; i++) h = (h * 33) ^ input.charCodeAt(i);
  return 'pg' + (h >>> 0).toString(36);
};

const pgSheetCache = new Set<string>();
let pgSheetEl: HTMLStyleElement | null = null;
const pgInject = (rule: string): void => {
  if (typeof document === 'undefined' || pgSheetCache.has(rule)) return;
  pgSheetCache.add(rule);
  if (!pgSheetEl) {
    pgSheetEl = document.createElement('style');
    pgSheetEl.id = 'pg-stylex';
    document.head.appendChild(pgSheetEl);
  }
  pgSheetEl.appendChild(document.createTextNode(rule));
};

const pgClassForProp = (prop: string, value: PGStyleValue): string => {
  const cls = pgHash(prop + ':' + JSON.stringify(value));
  if (value != null && typeof value === 'object') {
    for (const [cond, condVal] of Object.entries(value)) {
      if (condVal == null) continue;
      const decl = '.' + cls + pgPseudoSuffix(cond) + '{' + pgKebab(prop) + ':' + pgCssValue(prop, condVal) + '}';
      pgInject(pgWrapAtRule(cond, decl));
    }
  } else {
    pgInject('.' + cls + '{' + pgKebab(prop) + ':' + pgCssValue(prop, value) + '}');
  }
  return cls;
};

const pgPseudoSuffix = (cond: string): string =>
  cond === 'default' || cond.startsWith('@') ? '' : cond;

const pgWrapAtRule = (cond: string, decl: string): string =>
  cond.startsWith('@') ? cond + '{' + decl + '}' : decl;

const pgCompileRule = (rule: Record<string, unknown>): Record<string, unknown> => {
  const compiled: Record<string, unknown> = {$$css: true};
  for (const [prop, value] of Object.entries(rule)) {
    if (value == null) continue;
    compiled[prop] = pgClassForProp(prop, value as PGStyleValue);
  }
  return compiled;
};

const stylexMock = {
  create: <T extends Record<string, unknown>>(styles: T): T => {
    const out: Record<string, unknown> = {};
    for (const [key, rule] of Object.entries(styles)) {
      if (typeof rule === 'function') {
        // Dynamic styles must compile at call time so runtime values become classes.
        const fn = rule as (...args: unknown[]) => Record<string, unknown>;
        out[key] = (...args: unknown[]) => pgCompileRule(fn(...args));
      } else if (typeof rule === 'object' && rule != null) {
        out[key] = pgCompileRule(rule as Record<string, unknown>);
      } else {
        out[key] = rule;
      }
    }
    return out as T;
  },
  // Later styles override earlier ones per property key (matching real StyleX),
  // returning a className (not inline style) so @container/@media survive.
  props: (...styles: unknown[]) => {
    const byProp: Record<string, string> = {};
    for (const s of (styles.flat(Infinity) as unknown[])) {
      if (s == null || s === false || typeof s !== 'object') continue;
      for (const [prop, cls] of Object.entries(s as Record<string, unknown>)) {
        if (prop === '$$css' || typeof cls !== 'string') continue;
        byProp[prop] = cls;
      }
    }
    return {className: Object.values(byProp).join(' '), style: {}};
  },
  defineVars: <T extends Record<string, unknown>>(tokens: T): T => tokens,
  keyframes: (kf: Record<string, Record<string, string>>) => kf,
  types: {
    angle: (v: string) => v,
    color: (v: string) => v,
    image: (v: string) => v,
    integer: (v: string) => v,
    length: (v: string) => v,
    lengthPercentage: (v: string) => v,
    number: (v: string) => v,
    percentage: (v: string) => v,
    resolution: (v: string) => v,
    time: (v: string) => v,
    transformFunction: (v: string) => v,
    transformList: (v: string) => v,
    url: (v: string) => v,
  },
};`);
lines.push('');

// ── Component imports ──────────────────────────────────────────────────
for (const name of components) {
  lines.push(`import * as ${name} from '@khameleon/core/${name}';`);
}
lines.push('');

// ── Theme imports ──────────────────────────────────────────────────────
for (const t of SCOPE_THEMES) {
  lines.push(`import {${t.name}} from '${t.pkg}${t.subpath}';`);
}
lines.push('');

// ── Theme + tokens ──────────────────────────────────────────────────
lines.push("import {Theme} from '@khameleon/core/theme';");
lines.push("import type {DefinedTheme} from '@khameleon/core/theme';");
lines.push("import {createElement, type ComponentProps} from 'react';");
lines.push("import * as khameleonTokens from '@khameleon/core/theme/tokens.stylex';");
lines.push('');

// ── Hooks ──────────────────────────────────────────────────────────────
// camelCase, so the PascalCase component scan skips it — add it explicitly so
// templates using useMediaQuery etc. render.
lines.push("import * as Hooks from '@khameleon/core/hooks';");
lines.push('');

// ── Icon libraries ─────────────────────────────────────────────────────
lines.push("import * as LucideIcons from 'lucide-react';");
lines.push('// Heroicons kept available in the playground scope alongside Lucide');
lines.push("// so template / example code that still imports from");
lines.push("// '@heroicons/react/*' continues to render. New docsite code authors");
lines.push('// against Lucide; these entries are purely for backwards compat.');
for (const h of HEROICON_VARIANTS) {
  lines.push(`import * as ${h.alias} from '@heroicons/react/${h.path}';`);
}
lines.push('');

// ── ControlledTheme wrapper ─────────────────────────────────────────
const themeEntries = SCOPE_THEMES.map(
  (t) => `  ${t.name.replace('Theme', '').toLowerCase()}: ${t.name},`,
).join('\n');

lines.push(`const SCOPE_THEMES: Record<string, DefinedTheme> = {
${themeEntries}
};

const ControlledTheme = (props: ComponentProps<typeof Theme>) => {
  const win =
    typeof window !== 'undefined'
      ? (window as unknown as Record<string, unknown>)
      : null;
  const mode =
    (win?.__xds_preview_mode__ as 'light' | 'dark' | 'system') || 'system';
  const themeName = (win?.__xds_preview_theme__ as string) || 'default';
  const theme = SCOPE_THEMES[themeName] ?? ${SCOPE_THEMES[0].name};
  return createElement(Theme, {...props, theme, mode});
};`);
lines.push('');

// ── Scope map ──────────────────────────────────────────────────────────
lines.push('export const scope: Record<string, Record<string, unknown>> = {');

// react
lines.push(`  react: {
    default: React,
    ...React,
    useState,
    useCallback,
    useMemo,
    useEffect,
    useRef,
  },`);

// stylex
lines.push("  '@stylexjs/stylex': {default: stylexMock, ...stylexMock},");
lines.push("  stylex: {default: stylexMock, ...stylexMock},");

// themes
for (const t of SCOPE_THEMES) {
  lines.push(`  '${t.pkg}': {default: ${t.name}, ${t.name}},`);
  lines.push(`  '${t.pkg}/built': {default: ${t.name}, ${t.name}},`);
}

// Theme (controlled wrapper)
lines.push("  '@khameleon/core/theme': {Theme: ControlledTheme},");

// tokens.stylex
lines.push("  '@khameleon/core/theme/tokens.stylex': khameleonTokens,");

// hooks (useMediaQuery, etc.)
lines.push("  '@khameleon/core/hooks': Hooks,");

// Per-component subpath entries
for (const name of components) {
  lines.push(`  '@khameleon/core/${name}': ${name},`);
}

// Barrel export — all components spread
const spreads = components.map((n) => `    ...${n},`).join('\n');
lines.push(`  '@khameleon/core': {
${spreads}
  },`);

// Lucide icons + Heroicons
lines.push("  'lucide-react': LucideIcons,");
for (const h of HEROICON_VARIANTS) {
  lines.push(`  '@heroicons/react/${h.path}': ${h.alias},`);
}

// next/image stub
lines.push(`  'next/image': {
    default: (props: Record<string, unknown>) =>
      React.createElement('img', props),
  },`);

lines.push('};');
lines.push('');

// Write output
mkdirSync(dirname(OUT), {recursive: true});
writeFileSync(OUT, lines.join('\n'));
console.log(`✓ Generated ${OUT}`);
console.log(`  ${components.length} components`);
console.log(`  ${SCOPE_THEMES.length} themes`);
console.log(`  lucide-react icons + ${HEROICON_VARIANTS.length} heroicon variants`);
