// Copyright (c) 2026 the404. Part of the Khameleon design system (MIT).

/**
 * @file Builds the framework-agnostic Tailwind distribution of Khameleon.
 *
 * Outputs (to dist/):
 *   tokens.css   — every default design token extracted from the built
 *                  @khameleon/core stylesheet, re-emitted as plain `:root`
 *                  declarations (no component CSS, no StyleX classes), plus
 *                  appearance helpers for light/dark switching without React.
 *   theme.css    — the Tailwind v4 `@theme inline` bridge mapping Khameleon
 *                  tokens to Tailwind utility names (copied from core so this
 *                  package has no runtime dependency on @khameleon/core).
 *   preset.cjs   — a Tailwind v3 preset exposing the same names for projects
 *                  still on tailwind.config.js.
 *
 * Run from the package directory after @khameleon/core has been built.
 */

import * as fs from 'node:fs';
import * as path from 'node:path';
import {fileURLToPath} from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const PKG_ROOT = path.resolve(__dirname, '..');
const REPO_ROOT = path.resolve(PKG_ROOT, '..', '..');
const CORE_CSS = path.join(REPO_ROOT, 'packages', 'core', 'dist', 'khameleon.css');
const BRIDGE_CSS = path.join(REPO_ROOT, 'packages', 'core', 'src', 'tailwind-theme.css');
const OUT_DIR = path.join(PKG_ROOT, 'dist');

const coreCss = fs.readFileSync(CORE_CSS, 'utf8');

// StyleX emits default tokens as `:root, .<hash>{--a:v;--b:v;}` rule groups.
// Collect every declaration from those groups.
const rootRules = [...coreCss.matchAll(/:root,\s*\.[a-z0-9]+\{([^}]*)\}/g)];
if (rootRules.length === 0) {
  throw new Error('No :root token rules found in core CSS — build core first.');
}
const declarations = rootRules
  .map(m => m[1].trim().replace(/;$/, ''))
  .join(';\n  ')
  .split(';')
  .map(d => d.trim())
  .filter(Boolean);

const tokensCss = `/* @generated by @khameleon/tailwind build — do not edit.
 * All Khameleon default design tokens as plain custom properties.
 * Framework-agnostic: no React, no StyleX, no component CSS.
 * Layer a theme on top: @import '@khameleon/theme-khameleon/theme.css';
 */

:root {
  /* Tokens use light-dark(); this makes both schemes available by default. */
  color-scheme: light dark;
  ${declarations.join(';\n  ')};
}

/* Appearance control without the React <Theme> component: set
 * data-khameleon-appearance on <html> (or any subtree root). */
[data-khameleon-appearance='light'] {
  color-scheme: light;
}
[data-khameleon-appearance='dark'] {
  color-scheme: dark;
}
[data-khameleon-appearance='auto'] {
  color-scheme: light dark;
}
`;

// ---------------------------------------------------------------------------
// Tailwind v3 preset — same utility names as the v4 bridge, values via var().
// ---------------------------------------------------------------------------
const hueNames = [
  'blue', 'cyan', 'gray', 'green', 'orange',
  'pink', 'purple', 'red', 'teal', 'yellow',
];
const hueColors = {};
for (const hue of hueNames) {
  hueColors[`${hue}-subtle`] = `var(--color-background-${hue})`;
  hueColors[`${hue}-ring`] = `var(--color-border-${hue})`;
  hueColors[`${hue}-vivid`] = `var(--color-text-${hue})`;
}

const preset = {
  theme: {
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      primary: 'var(--color-text-primary)',
      secondary: 'var(--color-text-secondary)',
      disabled: 'var(--color-text-disabled)',
      accent: 'var(--color-text-accent)',
      surface: 'var(--color-background-surface)',
      body: 'var(--color-background-body)',
      card: 'var(--color-background-card)',
      popover: 'var(--color-background-popover)',
      muted: 'var(--color-background-muted)',
      inverted: 'var(--color-background-inverted)',
      overlay: 'var(--color-overlay)',
      'accent-bg': 'var(--color-accent)',
      'accent-muted': 'var(--color-accent-muted)',
      'on-accent': 'var(--color-on-accent)',
      neutral: 'var(--color-neutral)',
      'overlay-hover': 'var(--color-overlay-hover)',
      'overlay-pressed': 'var(--color-overlay-pressed)',
      'tint-hover': 'var(--color-tint-hover)',
      success: 'var(--color-success)',
      'success-muted': 'var(--color-success-muted)',
      'on-success': 'var(--color-on-success)',
      error: 'var(--color-error)',
      'error-muted': 'var(--color-error-muted)',
      'on-error': 'var(--color-on-error)',
      warning: 'var(--color-warning)',
      'warning-muted': 'var(--color-warning-muted)',
      'on-warning': 'var(--color-on-warning)',
      border: 'var(--color-border)',
      'border-strong': 'var(--color-border-emphasized)',
      'on-dark': 'var(--color-on-dark)',
      'on-light': 'var(--color-on-light)',
      skeleton: 'var(--color-skeleton)',
      track: 'var(--color-track)',
      shadow: 'var(--color-shadow)',
      ...hueColors,
    },
    borderColor: theme => ({
      ...theme('colors'),
      DEFAULT: 'var(--color-border)',
    }),
    fontFamily: {
      sans: 'var(--font-family-body)',
      mono: 'var(--font-family-code)',
      heading: 'var(--font-family-heading)',
    },
    fontSize: {
      '2xs': 'var(--font-size-2xs)',
      xs: 'var(--font-size-xs)',
      sm: 'var(--font-size-sm)',
      base: 'var(--font-size-base)',
      lg: 'var(--font-size-lg)',
      xl: 'var(--font-size-xl)',
      '2xl': 'var(--font-size-2xl)',
      '3xl': 'var(--font-size-3xl)',
      '4xl': 'var(--font-size-4xl)',
      '5xl': 'var(--font-size-5xl)',
    },
    fontWeight: {
      normal: 'var(--font-weight-normal)',
      medium: 'var(--font-weight-medium)',
      semibold: 'var(--font-weight-semibold)',
      bold: 'var(--font-weight-bold)',
    },
    borderRadius: {
      none: '0',
      xs: 'var(--radius-inner)',
      sm: 'var(--radius-inner)',
      DEFAULT: 'var(--radius-element)',
      md: 'var(--radius-element)',
      lg: 'var(--radius-container)',
      xl: 'var(--radius-page)',
      full: 'var(--radius-full)',
    },
    boxShadow: {
      sm: 'var(--shadow-low)',
      DEFAULT: 'var(--shadow-med)',
      md: 'var(--shadow-med)',
      lg: 'var(--shadow-high)',
      none: 'none',
    },
    extend: {
      spacing: {
        px: '1px',
        0: '0',
        0.5: 'var(--spacing-0-5)',
        1: 'var(--spacing-1)',
        1.5: 'var(--spacing-1-5)',
        2: 'var(--spacing-2)',
        3: 'var(--spacing-3)',
        4: 'var(--spacing-4)',
        5: 'var(--spacing-5)',
        6: 'var(--spacing-6)',
        7: 'var(--spacing-7)',
        8: 'var(--spacing-8)',
        9: 'var(--spacing-9)',
        10: 'var(--spacing-10)',
        11: 'var(--spacing-11)',
        12: 'var(--spacing-12)',
      },
    },
  },
};

const presetCjs = `// @generated by @khameleon/tailwind build — do not edit.
// Tailwind CSS v3 preset for the Khameleon design system.
// Usage (tailwind.config.js):
//   module.exports = { presets: [require('@khameleon/tailwind/preset')], ... }
// Requires tokens.css (and optionally a theme CSS) to be loaded on the page.

/* eslint-disable */
module.exports = ${JSON.stringify(preset, (k, v) =>
  typeof v === 'function' ? '__BORDER_FN__' : v, 2)
  .replace(
    '"__BORDER_FN__"',
    `(theme) => ({ ...theme('colors'), DEFAULT: 'var(--color-border)' })`,
  )};
`;

fs.mkdirSync(OUT_DIR, {recursive: true});
fs.writeFileSync(path.join(OUT_DIR, 'tokens.css'), tokensCss);
fs.copyFileSync(BRIDGE_CSS, path.join(OUT_DIR, 'theme.css'));
fs.writeFileSync(path.join(OUT_DIR, 'preset.cjs'), presetCjs);

console.log(
  `@khameleon/tailwind: wrote tokens.css (${declarations.length} tokens), theme.css, preset.cjs`,
);
